server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#spring:
#  messages: <1 key>
#  mvc: <1 key>
#  security:
#    user:
#      name: username
#      password: passw0rd
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-clas-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"