server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#spring:
#  messages: <1 key>
#  mvc: <1 key>
  security:
    user:
      name: username
      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"